### ISSUE TITLE
Memo

### ISSUE THREAD

**Issue by Xenolilly** [slu-soc5650/final-project#2]
I really wanted to map the sidewalks, but since that is not allowed, I do not know what to do. I downloaded some shapefiles from my county, but I do not know how to open them.  Picking final project is always incredibly difficult especially when I do not yet have the skills to use the tools required for the research. I don't know what I can and cannot do, until I have the skills, but I have to know before I have the skills.  I cannot, at this juncture, say I could do any project, with any degree of confidence.

**Comment by Xenolilly** [comment]
I will take on one of the standard final projects.

**Comment by chris-prener** [comment]
Hi @Xenolilly - 

Re: topic - did you look for other cities? I found [sidewalk data for Chicago](https://data.cityofchicago.org/widgets/77cn-6x4c), for example? If that works for you, I'd like to hear what you would want to show with it?

Re: skills mismatch - I hear you - I need you to trust a bit that I'm helping you work through the topic to make sure it fits in with where I want to students to be by the end of the semester. That's why I'm asking so many questions up-front, to make sure that you've got something that works by the time you've moved through the topic selection process.

-CP

**Comment by Xenolilly** [comment]
Thank you for your patience. I appreciate you finding the Chicago data. I had found New York sidewalk data previously. I wanted sidewalks specifically because I want to do my master's thesis on local accessibility. I want it to be local so I can hopefully interview local people and experience the walks firsthand. Although, perhaps Chicago would still be useful as a point of learning GIS. Nevertheless, I think I will still go with one of the standard projects.  I do not want to waste time figuring out the details. I will likely use the Chicago data for reference for other projects. Again, I very much appreciate the extra mile you put in finding that for me.

**Comment by chris-prener** [comment]
OK - that's fine with me! I'd strongly encourage you to pick some sidewalk-related issues from the CSB data, then, to keep you in the same neighborhood as your thesis.

**Comment by chris-prener** [comment]
@Xenolilly - can you move this over to your individual [final project repository](https://github.com/slu-soc5650/AMurphyProject/issues) once you've got a handle on the specific CSB codes (or other data) you intended to use? thanks!
